version: '4'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_graphql
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword     # Root password
      MYSQL_DATABASE: product     # Database to create
      MYSQL_USER: aakash                # Non-root user to create
      MYSQL_PASSWORD: aakashadmin        # Password for the user
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    container_name: adminer_spring_graphql
    restart: always
    ports:
      - "9089:8080"